version: '3.7'

services:
  config-manager:
    image: aerokube/cm:latest
    container_name: selenoid-config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/selenoid
    networks:
      - selenoid-net
    command: [ "selenoid", "configure", "--browsers", "chrome", "--last-versions", "2", "--config-dir", "/etc/selenoid", "--force" ]

  selenoid:
    image: aerokube/selenoid:latest
    depends_on:
      - config-manager
    ports:
      - "4444:4444"
    volumes:
      - ./config:/etc/selenoid:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/opt/selenoid/logs
      - ./video:/opt/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "10", "-timeout", "3m", "-video-output-dir", "/opt/selenoid/video", "-container-network", "selenoid-net" ]
    networks:
      - selenoid-net

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    environment:
      - SELENOID_URI=http://selenoid:4444
    networks:
      - selenoid-net
    links:
      - selenoid
    command:
      - "--selenoid-uri"
      - "http://selenoid:4444"
networks:
  selenoid-net:
    driver: bridge
    external: true
